### ISSUE TITLE
Mappers and settings

### ISSUE THREAD

**Issue by jonbra** [vtsyvina/CliqueSNV#17]
Hi, 
Have you experimented with different mappers and settings to generate the bam file? How important is accurate mapping for CliqueSNV? Do you have any recommendations for illumina reads? 
Thanks, Jon

**Comment by Sergey-Knyazev** [comment]
Hi Jon,
This is a good question because accurate mapping is important since it can generate some systematic errors. For Illumina reads, for samples from viruses, we reduced mismatch penalty because mutations in viruses are more expected than in other organisms. As of other parameters, we used default values. We also tried to use tablet for raw quality estimation of alignment by controlling visually dependence of coverage on parameters.

**Comment by jonbra** [comment]
Thanks. We're testing a little bit the difference between Bowtie2 and Tanoti. Tanoti is very sensitive and designed for fast evolving viruses. It looks like we get fewer haplotypes predicted with Tanoti compared to Bowtie2, but these are very prelimiary results.

**Comment by Sergey-Knyazev** [comment]
Thank you for sharing that! If you believe that Tanoti is more accurate than Bowtie2, then it makes sense why it produces less haplotypes on Tanoti alignment. The reason could be the systematic errors as I mentioned. However, it is only an intuition, to get better answer, it may require a more thorough analysis. Thank you!
